### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by wobbol** [ErgoDox/tmk_ErgoDox#16]
Write a semantic versioning rfc specific to this project.

**Comment by marknsikora** [comment]
Personally I test changes on my own board for ~2 weeks before pushing them and tell users that bleeding edge is stable

**Comment by marknsikora** [comment]
Just read #14, my preference would be a single master branch with tags for stable versions or after some major feature addition. Eg tag v9, v10, v11, etc.
