### ISSUE TITLE
Fork ErgoDox design files

### ISSUE THREAD

**Issue by wobbol** [ErgoDox/tmk_ErgoDox#18]
I think it would be best if this org had a fork of the design files hanging around as they have not been updated in years it should be relatively low maintenance.

**Comment by marknsikora** [comment]
Well ergodox.org seems to be down. And they had a robots.txt that prevented it being cached anywhere. So this will require some hunting.

**Comment by wobbol** [comment]
Done, found it here https://github.com/bishboria/ErgoDox
I guess since the Org name is ErgoDox we should have a copy.
