### ISSUE TITLE
Layout stratagy

### ISSUE THREAD

**Issue by wobbol** [ErgoDox/tmk_ErgoDox#20]
I think a cool way to reduce the visual noise in the repo is to have a terminal script that takes [a-z], mod key, and [0-9] layout options Q & A style and writes a keymap_<name>.<layer> then, another script that combines keymap_<name>.<layer> into a keymap_<name>.c

<layer> can be a descriptive name that the user can save for later revisions of their keyboard stack. This variable will be used in other keymap_<name>.<layer> files to link layers together in a meaningful way.

**Comment by wobbol** [comment]
Compare and contrast to the vi keys node application.

**Comment by marknsikora** [comment]
Not sure what you mean by this

**Comment by wobbol** [comment]
I mean, break down each keymap layer into chunks that make sense for storage and remixing? After more thought the idea seems half baked.
This is an advanced feature that would fit better in a layout create-er/manager than a tool by itself.
